"""Emit aster_edge/index.html with deterministic layout bulk."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "index.html"

SPECIES = [
    ("EmberPeep", 11, 9, 10, 1),
    ("AquaCluck", 9, 11, 10, 2),
    ("LeafWing", 10, 10, 11, 3),
    ("SparkHen", 12, 8, 11, 4),
    ("FrostBrood", 8, 12, 9, 5),
    ("StoneRoost", 10, 13, 7, 6),
    ("GalePullet", 11, 8, 12, 1),
    ("ShadowCoop", 13, 9, 9, 7),
    ("SunComb", 10, 10, 10, 1),
    ("MoonBrooder", 9, 12, 10, 7),
    ("ThunderPeck", 14, 8, 10, 4),
    ("MossRunner", 9, 10, 12, 3),
    ("CrystalHen", 10, 11, 10, 8),
    ("MagmaWattle", 13, 9, 8, 1),
    ("TideCaller", 8, 11, 11, 2),
    ("BrambleBeak", 11, 10, 9, 3),
    ("VoltNest", 12, 9, 11, 4),
    ("GlacierLayer", 8, 13, 9, 5),
    ("QuartzCluck", 10, 12, 9, 8),
    ("DustDevil", 11, 9, 11, 6),
    ("StarlingChick", 9, 9, 13, 7),
    ("CometCrest", 12, 10, 9, 1),
    ("NebulaYolk", 10, 9, 12, 7),
    ("IonPeep", 13, 8, 11, 4),
    ("RootGuard", 9, 13, 9, 3),
    ("SiltStrider", 10, 10, 11, 6),
    ("BrineFang", 8, 10, 13, 2),
    ("CinderCrown", 14, 9, 8, 1),
    ("ZephyrDown", 9, 8, 14, 1),
    ("RuneRooster", 11, 11, 9, 8),
    ("EchoWing", 10, 9, 11, 7),
    ("PulseHen", 12, 10, 10, 4),
    ("FernShield", 8, 14, 9, 3),
    ("BasaltBeak", 11, 12, 8, 6),
    ("MirageLayer", 10, 9, 12, 7),
    ("TundraTalons", 9, 12, 10, 5),
    ("SolarFlare", 15, 8, 9, 1),
    ("AbyssalCluck", 9, 11, 11, 2),
    ("VerdantStrike", 11, 9, 11, 3),
    ("StormCrest", 13, 9, 10, 4),
    ("ObsidianBrood", 10, 13, 8, 6),
    ("LumenPeep", 9, 10, 12, 8),
    ("DuskRunner", 12, 9, 10, 7),
    ("GaleShard", 11, 10, 10, 4),
    ("MarshWarden", 9, 12, 10, 3),
    ("CoralCaller", 8, 11, 12, 2),
    ("EmberVault", 12, 11, 8, 1),
    ("IronFeather", 10, 14, 7, 6),
    ("VoidYolk", 13, 8, 11, 7),
]

MOVE_NAMES = [
    (1, "Peck Flick"),
    (2, "Dust Up"),
    (3, "Wing Buffer"),
    (4, "Seed Toss"),
    (5, "Beak Glint"),
    (6, "Cluck Pulse"),
    (7, "Strut Bash"),
    (8, "Spark Line"),
    (9, "Puddle Hop"),
    (10, "Static Down"),
    (11, "Barn Sweep"),
    (12, "Haymaker"),
    (13, "Drift Peck"),
    (14, "Gust Turn"),
    (15, "Stone Stomp"),
    (16, "Frost Ruffle"),
    (17, "Moss Wrap"),
    (18, "Tide Slap"),
    (19, "Shadow Dart"),
    (20, "Sun Flare"),
    (21, "Moon Hook"),
    (22, "Combo Rush"),
    (23, "Guarded Peck"),
    (24, "Tempo Swap"),
    (25, "Counter Coop"),
    (26, "League Finale"),
    (27, "Yolk Surge"),
    (28, "Crest Spin"),
    (29, "Brood Wall"),
    (30, "Arena Echo"),
    (31, "Vault Strike"),
    (32, "Void Tap"),
]

COACHING_TIPS = [
    "Bank grain before tournament weeks so training never stalls mid-bracket.",
    "Swap move slots after every evolution to cover new elemental spreads.",
    "Lead with tempo-heavy chicks when the opponent stacks guard.",
    "If you see frost-heavy benches, bring spark-line attackers with backup aqua coverage.",
    "Shadow broods punish careless spark spam — pack crystal finishers for late rounds.",
    "Stone roost lines love long stalls; break them with plant tempo flips.",
    "Keep at least one neutral-power bird to soak bad type matchups in blind picks.",
    "When leveling slows near 40, pivot to spar XP instead of pure forage loops.",
    "Rename birds early so JSON exports stay human-readable in guild tools.",
    "Use the entropy box to reproduce spars when filing bug reports against sims.",
    "Export roster JSON before browser refreshes; localStorage is intentionally unused here.",
    "Train might on glass cannons, guard on anchors, tempo on sweepers — not uniformly.",
    "Watch streak counters: they are morale proxies in this league flavor.",
    "If vitality lags, simulate feeding bursts before running five blitz spars.",
    "Crystal-type crest moves swing mirror matches — slot one per team.",
    "Moon brooders love night buffs in the Python trainer; on-chain ignores diurnal fluff.",
    "Avoid relying on miner bias — mainnet entropy differs from browser PRNG mocks.",
    "League pot donations on-chain require value; this page never sends ETH by itself.",
    "ADDRESS hints in the header mirror immutables baked into ChickCombo's constructor.",
    "Rotate species IDs in scrims to learn the full almanac, not just comfort picks.",
    "Use CSV exports when sharing lineups with non-technical coaches.",
    "If imports fail, validate JSON braces and trainer field first.",
    "Blitz mode is a stress test; pause if logs grow unreadable.",
    "Keep defender tempo high when facing might-heavy sweepers.",
    "Pack at least one low-base-might bird with huge grain income for economy games.",
    "Spar cooldown awareness saves gas grief on real settlements later.",
    "Evolution gates are strict: level 18 plus 900 XP before evolving.",
    "Move codes above 32 are rejected on-chain; keep slots honest.",
    "When testing type charts, cross-check lattice table against your mental model.",
    "Shadow > nothing is false — shadow participates in a tight triangle like others.",
    "Use matchup prediction helpers before committing to mint transactions.",
    "If roster diversity score is low, hatch missing elements before ranked play.",
    "Bench clears are destructive; export first.",
    "Power score heuristic here is might*2+guard+tempo — not identical to chain internals.",
    "Browser crypto entropy is adequate for UI drills, not for custody games.",
    "If animations stutter, reduce flakes by editing initFx density in source.",
    "League tag constants differ from other contracts — do not reuse salts elsewhere.",
    "Grain floor drills help you understand train_until loops in the Python app.",
    "When sparring, attacker might plus half tempo models aggressive pacing.",
    "Defender guard plus third tempo rewards stonewall builds.",
    "Type advantage adds a flat swing — enough to flip close rolls.",
    "XP gains on wins exceed losses; still farm responsibly.",
    "Nickname collisions are warnings in Python; rename to stay organized.",
    "Use scouting reports before merges when combining trainer JSON files.",
    "If you fork the UI, restyle tokens but keep accessibility contrast high.",
    "Keyboard users: tab across selects before hitting spar for predictable order.",
    "Screen readers: battle log is plain text; avoid relying on color alone.",
    "Void yolk species hits hard; respect its element when sideboarding.",
    "Iron feather skews guard — excellent into mixed assault teams.",
    "Coral callers love aqua tempo — test them against frost anchors.",
    "Marsh wardens stabilize plant lines with thick guard buffers.",
    "Gale shard spreads electric tempo without dumping guard completely.",
    "Dusk runners are shadow-streaked; bring crystal answers.",
    "Lumen peeps shine in crystal mirrors; pack diversity.",
    "Obsidian brood stonewalls; break with sustained might pressure.",
    "Storm crest offers spark consistency; watch water counters.",
    "Verdant strike is the plant tempo answer to brawlers.",
    "Abyssal cluck balances aqua bulk and tempo — great flex slot.",
    "Solar flare hits like a truck; keep grain to recover after spars.",
